//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountuser
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string useremail { get; set; }
        public string userpwd { get; set; }
        public string usermobile { get; set; }
        public string userdepart { get; set; }
        public string userrealname { get; set; }
        public string usernum { get; set; }
        public string userkey { get; set; }
        public string captcha { get; set; }
        public Nullable<int> isverify { get; set; }
    }
}
