//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class advise
    {
        public int id { get; set; }
        public string sex { get; set; }
        public string grade { get; set; }
        public string text { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string android_version { get; set; }
        public string mobile_model { get; set; }
        public string density { get; set; }
    }
}
