//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataInfo : DbContext
    {
        public DataInfo()
            : base("name=DataInfo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<advise> advise { get; set; }
        public DbSet<busInfo> busInfo { get; set; }
        public DbSet<lecture> lecture { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<post> post { get; set; }
        public DbSet<postback> postback { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<version> version { get; set; }
        public DbSet<weather> weather { get; set; }
        public DbSet<nearbyeating> nearbyeating { get; set; }
        public DbSet<nearbygoing> nearbygoing { get; set; }
        public DbSet<nearbyliving> nearbyliving { get; set; }
        public DbSet<nearbyother> nearbyother { get; set; }
        public DbSet<nearbyplaying> nearbyplaying { get; set; }
        public DbSet<OFFICE> OFFICE { get; set; }
        public DbSet<ROOM> ROOM { get; set; }
        public DbSet<TEACHER> TEACHER { get; set; }
        public DbSet<OFFICEUSE_TEACHER> OFFICEUSE_TEACHER { get; set; }
        public DbSet<ROOMUSE_TEACHER> ROOMUSE_TEACHER { get; set; }
        public DbSet<LOCATION> LOCATION { get; set; }
        public DbSet<job> job { get; set; }
    }
}
