//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int id { get; set; }
        public string infotitile { get; set; }
        public string jobtime { get; set; }
        public string jobdetail { get; set; }
        public string jobrequire { get; set; }
        public string jobsite { get; set; }
        public string jobtreatment { get; set; }
        public string jobtag { get; set; }
        public string releasetime { get; set; }
        public string qinban_cert { get; set; }
        public string via { get; set; }
    }
}
