//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecture_____
    {
        public int no { get; set; }
        public string name { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<int> start { get; set; }
        public Nullable<int> endd { get; set; }
        public string time { get; set; }
        public string classroom { get; set; }
        public string teacher { get; set; }
        public string department { get; set; }
        public string campus { get; set; }
    }
}
