//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecture
    {
        public int id { get; set; }
        public string lecturetitle { get; set; }
        public Nullable<System.DateTime> lecturetime { get; set; }
        public string campus { get; set; }
        public string lecturesite { get; set; }
        public string reporter { get; set; }
        public string depart { get; set; }
        public string remark { get; set; }
    }
}
