//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public int LOCATIONID { get; set; }
        public string LOCATIONNAME { get; set; }
        public string NOTE { get; set; }
        public string LONGTITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string LL { get; set; }
        public string CAMPUS { get; set; }
    }
}
