//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class nearbyliving
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string introduction { get; set; }
        public string detail { get; set; }
        public string location { get; set; }
        public string longtitude { get; set; }
        public string latitude { get; set; }
        public string phone { get; set; }
        public string ll { get; set; }
        public Nullable<bool> campus { get; set; }
    }
}
