//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public int ROOMID { get; set; }
        public string ROOMNAME { get; set; }
        public string ROOMLOCATION { get; set; }
        public string ROOMTYPE { get; set; }
        public string CAMPUS { get; set; }
        public string PHONE { get; set; }
    }
}
