//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMUSE_TEACHER
    {
        public int ROOMID { get; set; }
        public string CLASSNAME { get; set; }
        public string TEACHERID { get; set; }
        public string WEEKDAYTIME { get; set; }
        public string NOTE { get; set; }
    
        public virtual ROOM ROOM { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
