//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomEmpty
    {
        public int id { get; set; }
        public string wday { get; set; }
        public string during { get; set; }
        public bool isempty { get; set; }
        public string detail { get; set; }
    
        public virtual roomInfo roomInfo { get; set; }
    }
}
