//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string h12 { get; set; }
        public string h12temp { get; set; }
        public string h12img1 { get; set; }
        public string h12img2 { get; set; }
        public string h24 { get; set; }
        public string h24temp { get; set; }
        public string h24img1 { get; set; }
        public string h24img2 { get; set; }
        public string aqi { get; set; }
        public Nullable<int> pm25 { get; set; }
    }
}
